use crate::data::Context;
use clap_complete::engine::CompletionCandidate;
use std::collections::BTreeSet;
use std::ffi::OsStr;
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicU64, Ordering};

const BASH_LOADER: &str = r#"# Generated by codex-switch. Saved profile names are completed at runtime.
source <(CODEX_SWITCH_COMPLETE=bash codex-switch)
"#;

#[derive(Clone, Copy)]
enum ProfileCandidates {
    All,
    Codex,
    Pi,
    References,
    AutoPolicies,
    Transfers,
}

pub fn all_profiles() -> Vec<CompletionCandidate> {
    runtime_candidates(ProfileCandidates::All)
}

pub fn codex_profiles() -> Vec<CompletionCandidate> {
    runtime_candidates(ProfileCandidates::Codex)
}

pub fn pi_profiles() -> Vec<CompletionCandidate> {
    runtime_candidates(ProfileCandidates::Pi)
}

pub fn profile_references() -> Vec<CompletionCandidate> {
    runtime_candidates(ProfileCandidates::References)
}

pub fn auto_profiles() -> Vec<CompletionCandidate> {
    runtime_candidates(ProfileCandidates::AutoPolicies)
}

pub fn transfer_profiles() -> Vec<CompletionCandidate> {
    runtime_candidates(ProfileCandidates::Transfers)
}

pub fn remove_profiles() -> Vec<CompletionCandidate> {
    let args: Vec<_> = completion_args().collect();
    let kind = args.windows(3).find_map(|words| match words {
        [profile, remove, store] if profile == "profile" && remove == "remove" => {
            match store.to_str() {
                Some("codex") => Some(ProfileCandidates::Codex),
                Some("pi") => Some(ProfileCandidates::Pi),
                _ => None,
            }
        }
        _ => None,
    });
    kind.map(runtime_candidates).unwrap_or_default()
}

#[cfg(not(test))]
fn completion_args() -> impl Iterator<Item = std::ffi::OsString> {
    std::env::args_os()
}

#[cfg(test)]
fn completion_args() -> impl Iterator<Item = std::ffi::OsString> {
    TEST_ARGS.with(|args| args.borrow().clone().into_iter())
}

fn runtime_candidates(kind: ProfileCandidates) -> Vec<CompletionCandidate> {
    let Some(home) = runtime_home() else {
        return Vec::new();
    };
    let state_dir = home.join(".local/state/codex-switch");
    let ctx = Context {
        live_auth: home.join(".codex/auth.json"),
        pi_auth: home.join(".pi/agent/auth.json"),
        tracker_file: state_dir.join("accounts.json"),
        state_dir,
    };
    candidates(&ctx, kind)
        .into_iter()
        .map(CompletionCandidate::new)
        .collect()
}

#[cfg(not(test))]
fn runtime_home() -> Option<PathBuf> {
    std::env::var_os("HOME")
        .filter(|home| !home.is_empty())
        .map(PathBuf::from)
}

#[cfg(test)]
thread_local! {
    static TEST_HOME: std::cell::RefCell<Option<PathBuf>> = const { std::cell::RefCell::new(None) };
    static TEST_ARGS: std::cell::RefCell<Vec<std::ffi::OsString>> = const { std::cell::RefCell::new(Vec::new()) };
}

#[cfg(test)]
fn runtime_home() -> Option<PathBuf> {
    TEST_HOME.with(|home| home.borrow().clone())
}

fn candidates(ctx: &Context, kind: ProfileCandidates) -> Vec<String> {
    let codex = names(crate::profile::list_profiles(ctx));
    let pi = names(crate::profile::list_pi_profiles(ctx));
    let values = match kind {
        ProfileCandidates::All => codex.union(&pi).cloned().collect(),
        ProfileCandidates::Codex => codex,
        ProfileCandidates::Pi => pi,
        ProfileCandidates::References => {
            let mut refs = BTreeSet::from(["codex/".to_string(), "pi/".to_string()]);
            refs.extend(codex.into_iter().map(|name| format!("codex/{name}")));
            refs.extend(pi.into_iter().map(|name| format!("pi/{name}")));
            refs
        }
        ProfileCandidates::AutoPolicies => option_names(ctx, |option| option.auto.is_some()),
        ProfileCandidates::Transfers => option_names(ctx, |option| option.transfer.is_some()),
    };
    values.into_iter().collect()
}

fn names(paths: Vec<PathBuf>) -> BTreeSet<String> {
    paths
        .into_iter()
        .filter(|path| path.is_file())
        .map(|path| crate::profile::profile_name(&path))
        .filter(|name| crate::switch::validate_profile_name(name).is_ok())
        .collect()
}

fn option_names(
    ctx: &Context,
    keep: impl Fn(&crate::profile_options::ProfileOption) -> bool,
) -> BTreeSet<String> {
    crate::profile_options::load_read_only(ctx)
        .unwrap_or_default()
        .profiles
        .into_iter()
        .filter(|(name, option)| crate::switch::validate_profile_name(name).is_ok() && keep(option))
        .map(|(name, _)| name)
        .collect()
}

pub fn bash_script() -> &'static str {
    BASH_LOADER
}

pub fn completion_path(
    xdg_data_home: Option<&OsStr>,
    home: Option<&OsStr>,
) -> Result<PathBuf, String> {
    let xdg_data_home = xdg_data_home
        .filter(|value| !value.is_empty())
        .map(PathBuf::from)
        .filter(|path| path.is_absolute());
    let data_home = match xdg_data_home {
        Some(path) => path,
        None => {
            let home = PathBuf::from(
                home.filter(|value| !value.is_empty())
                    .ok_or("HOME is not set and XDG_DATA_HOME is unavailable")?,
            );
            if !home.is_absolute() {
                return Err("HOME must be an absolute path".to_string());
            }
            home.join(".local/share")
        }
    };
    Ok(data_home.join("bash-completion/completions/codex-switch"))
}

pub fn default_completion_path() -> Result<PathBuf, String> {
    completion_path(
        std::env::var_os("XDG_DATA_HOME").as_deref(),
        std::env::var_os("HOME").as_deref(),
    )
}

pub fn install_bash(path: &Path, force: bool) -> Result<bool, String> {
    install_bash_with(path, force, || {})
}

static TEMP_SEQUENCE: AtomicU64 = AtomicU64::new(0);

fn install_bash_with(
    path: &Path,
    force: bool,
    before_publish: impl FnOnce(),
) -> Result<bool, String> {
    let destination_exists = match std::fs::symlink_metadata(path) {
        Ok(_) => true,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => false,
        Err(error) => return Err(format!("failed to inspect {}: {error}", path.display())),
    };
    if destination_exists {
        match std::fs::read(path) {
            Ok(existing) if existing == BASH_LOADER.as_bytes() => return Ok(false),
            Ok(_) if !force => {
                return Err(format!(
                    "completion file {} already exists with different content; use --force to replace it",
                    path.display()
                ));
            }
            Err(error) if !force => {
                return Err(format!("failed to read {}: {error}", path.display()));
            }
            _ => {}
        }
    }

    let parent = path
        .parent()
        .filter(|parent| !parent.as_os_str().is_empty())
        .ok_or_else(|| format!("completion path {} has no parent", path.display()))?;
    std::fs::create_dir_all(parent)
        .map_err(|error| format!("failed to create {}: {error}", parent.display()))?;

    let (temp, mut file) = (0..100)
        .find_map(|_| {
            let sequence = TEMP_SEQUENCE.fetch_add(1, Ordering::Relaxed);
            let temp = parent.join(format!(
                ".codex-switch.tmp-{}-{sequence}",
                std::process::id()
            ));
            match std::fs::OpenOptions::new()
                .write(true)
                .create_new(true)
                .open(&temp)
            {
                Ok(file) => Some(Ok((temp, file))),
                Err(error) if error.kind() == std::io::ErrorKind::AlreadyExists => None,
                Err(error) => Some(Err(format!("failed to create {}: {error}", temp.display()))),
            }
        })
        .unwrap_or_else(|| Err("failed to allocate a temporary completion file".to_string()))?;

    use std::io::Write;
    let write_result = file
        .write_all(BASH_LOADER.as_bytes())
        .and_then(|()| file.sync_all());
    if let Err(error) = write_result {
        let _ = std::fs::remove_file(&temp);
        return Err(format!("failed to write {}: {error}", temp.display()));
    }
    drop(file);
    before_publish();

    let result = if force {
        std::fs::rename(&temp, path)
    } else {
        // hard_link is an atomic create-if-absent operation: unlike rename, it can never
        // replace a destination created after the initial inspection.
        let result = std::fs::hard_link(&temp, path);
        let _ = std::fs::remove_file(&temp);
        result
    };
    if let Err(error) = result {
        let _ = std::fs::remove_file(&temp);
        let detail = if !force && error.kind() == std::io::ErrorKind::AlreadyExists {
            "destination appeared while installing; use --force to replace it".to_string()
        } else {
            error.to_string()
        };
        return Err(format!("failed to install {}: {detail}", path.display()));
    }
    Ok(true)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::profile_options::{
        AutoSwitchPolicy, ProfileOption, ProfileOptions, TransferOnSwitchPolicy,
    };
    use clap::CommandFactory;
    use std::collections::BTreeMap;

    fn context(name: &str) -> (Context, PathBuf) {
        let base = std::env::temp_dir().join(format!(
            "codex-switch-completion-{name}-{}",
            std::process::id()
        ));
        let _ = std::fs::remove_dir_all(&base);
        let state_dir = base.join("state");
        (
            Context {
                live_auth: base.join("auth.json"),
                pi_auth: base.join("pi.json"),
                tracker_file: state_dir.join("accounts.json"),
                state_dir,
            },
            base,
        )
    }

    #[test]
    fn collects_valid_sorted_profile_candidates_and_references() {
        let (ctx, base) = context("candidates");
        std::fs::create_dir_all(ctx.codex_profiles_dir()).unwrap();
        std::fs::create_dir_all(ctx.pi_profiles_dir()).unwrap();
        for name in ["zeta", "shared", "bad.name"] {
            std::fs::write(ctx.profile_path(name), "{}").unwrap();
        }
        for name in ["alpha", "shared"] {
            std::fs::write(ctx.pi_profile_path(name), "{}").unwrap();
        }
        std::fs::create_dir(ctx.profile_path("directory")).unwrap();
        assert_eq!(
            candidates(&ctx, ProfileCandidates::All),
            ["alpha", "shared", "zeta"]
        );
        assert_eq!(
            candidates(&ctx, ProfileCandidates::Codex),
            ["shared", "zeta"]
        );
        assert_eq!(candidates(&ctx, ProfileCandidates::Pi), ["alpha", "shared"]);
        assert_eq!(
            candidates(&ctx, ProfileCandidates::References),
            [
                "codex/",
                "codex/shared",
                "codex/zeta",
                "pi/",
                "pi/alpha",
                "pi/shared"
            ]
        );
        std::fs::remove_dir_all(base).unwrap();
    }

    #[test]
    fn policy_candidates_are_read_only_and_filtered() {
        let (ctx, base) = context("policies");
        std::fs::create_dir_all(&ctx.state_dir).unwrap();
        let mut profiles = BTreeMap::new();
        profiles.insert(
            "auto".into(),
            ProfileOption {
                auto: Some(AutoSwitchPolicy::default()),
                transfer: None,
            },
        );
        profiles.insert(
            "mapped".into(),
            ProfileOption {
                auto: None,
                transfer: Some(TransferOnSwitchPolicy {
                    enabled: false,
                    pi_profile: "target".into(),
                }),
            },
        );
        profiles.insert(
            "bad/name".into(),
            ProfileOption {
                auto: Some(AutoSwitchPolicy::default()),
                transfer: None,
            },
        );
        crate::profile_options::save(&ctx, &ProfileOptions { profiles }).unwrap();
        assert_eq!(candidates(&ctx, ProfileCandidates::AutoPolicies), ["auto"]);
        assert_eq!(candidates(&ctx, ProfileCandidates::Transfers), ["mapped"]);
        std::fs::remove_file(ctx.profile_options_path()).unwrap();
        std::fs::write(
            ctx.state_dir.join("auto-profiles.json"),
            r#"{"profiles":{"legacy":{}}}"#,
        )
        .unwrap();
        assert_eq!(
            candidates(&ctx, ProfileCandidates::AutoPolicies),
            ["legacy"]
        );
        assert!(!ctx.profile_options_path().exists());
        std::fs::remove_dir_all(base).unwrap();
    }

    fn engine_values(home: &Path, words: &[&str]) -> Vec<String> {
        TEST_HOME.with(|value| *value.borrow_mut() = Some(home.to_path_buf()));
        TEST_ARGS.with(|value| {
            *value.borrow_mut() = words.iter().map(std::ffi::OsString::from).collect()
        });
        let args = words.iter().map(std::ffi::OsString::from).collect();
        let values = clap_complete::engine::complete(
            &mut crate::cli::Cli::command(),
            args,
            words.len() - 1,
            Some(home),
        )
        .unwrap()
        .into_iter()
        .map(|candidate| candidate.get_value().to_string_lossy().into_owned())
        .filter(|candidate| !candidate.starts_with('-'))
        .collect();
        TEST_HOME.with(|value| *value.borrow_mut() = None);
        TEST_ARGS.with(|value| value.borrow_mut().clear());
        values
    }

    #[test]
    fn dynamic_engine_completes_every_profile_context() {
        let (_ctx, home) = context("engine");
        let state = home.join(".local/state/codex-switch");
        let ctx = Context {
            live_auth: home.join(".codex/auth.json"),
            pi_auth: home.join(".pi/agent/auth.json"),
            tracker_file: state.join("accounts.json"),
            state_dir: state,
        };
        std::fs::create_dir_all(ctx.codex_profiles_dir()).unwrap();
        std::fs::create_dir_all(ctx.pi_profiles_dir()).unwrap();
        std::fs::write(ctx.profile_path("codex-only"), "{}").unwrap();
        std::fs::write(ctx.pi_profile_path("pi-only"), "{}").unwrap();
        let mut profiles = BTreeMap::new();
        profiles.insert(
            "automatic".into(),
            ProfileOption {
                auto: Some(AutoSwitchPolicy::default()),
                transfer: None,
            },
        );
        profiles.insert(
            "mapped".into(),
            ProfileOption {
                auto: None,
                transfer: Some(TransferOnSwitchPolicy {
                    enabled: true,
                    pi_profile: "pi-only".into(),
                }),
            },
        );
        crate::profile_options::save(&ctx, &ProfileOptions { profiles }).unwrap();

        for words in [
            &["codex-switch", ""][..],
            &["codex-switch", "switch", ""][..],
            &["codex-switch", "auto", "set", ""][..],
        ] {
            let values = engine_values(&home, words);
            assert!(
                values.contains(&"codex-only".to_string()),
                "{words:?}: {values:?}"
            );
            assert!(
                values.contains(&"pi-only".to_string()),
                "{words:?}: {values:?}"
            );
        }
        assert_eq!(
            engine_values(&home, &["codex-switch", "auto", "remove", ""]),
            ["automatic"]
        );
        let codex_remove =
            engine_values(&home, &["codex-switch", "profile", "remove", "codex", ""]);
        assert!(codex_remove.contains(&"codex-only".to_string()));
        assert!(!codex_remove.contains(&"pi-only".to_string()));
        let pi_remove = engine_values(&home, &["codex-switch", "profile", "remove", "pi", ""]);
        assert_eq!(pi_remove, ["pi-only"]);

        for words in [
            &["codex-switch", "profile", "transfer", "now", ""][..],
            &[
                "codex-switch",
                "profile",
                "transfer",
                "now",
                "codex/codex-only",
                "",
            ][..],
        ] {
            let values = engine_values(&home, words);
            assert!(values.contains(&"codex/codex-only".to_string()));
            assert!(values.contains(&"pi/pi-only".to_string()));
        }
        let set_source = engine_values(
            &home,
            &[
                "codex-switch",
                "profile",
                "transfer",
                "on-switch",
                "set",
                "",
            ],
        );
        assert!(set_source.contains(&"codex-only".to_string()));
        assert!(!set_source.contains(&"pi-only".to_string()));
        assert_eq!(
            engine_values(
                &home,
                &[
                    "codex-switch",
                    "profile",
                    "transfer",
                    "on-switch",
                    "set",
                    "codex-only",
                    "",
                ],
            ),
            ["pi-only"]
        );
        for action in ["enable", "disable"] {
            assert_eq!(
                engine_values(
                    &home,
                    &[
                        "codex-switch",
                        "profile",
                        "transfer",
                        "on-switch",
                        action,
                        "",
                    ],
                ),
                ["mapped"]
            );
        }
        std::fs::remove_dir_all(home).unwrap();
    }

    #[test]
    fn runtime_entry_points_are_empty_without_a_home() {
        TEST_HOME.with(|home| *home.borrow_mut() = None);
        TEST_ARGS.with(|args| {
            *args.borrow_mut() = ["codex-switch", "profile", "remove", "codex", ""]
                .into_iter()
                .map(std::ffi::OsString::from)
                .collect()
        });
        for values in [
            all_profiles(),
            codex_profiles(),
            pi_profiles(),
            profile_references(),
            auto_profiles(),
            transfer_profiles(),
            remove_profiles(),
        ] {
            assert!(values.is_empty());
        }
        TEST_ARGS.with(|args| args.borrow_mut().clear());
    }

    #[test]
    fn resolves_standard_completion_paths() {
        let expected = Path::new("/tmp/home/.local/share/bash-completion/completions/codex-switch");
        assert_eq!(
            completion_path(Some(OsStr::new("/tmp/data")), None).unwrap(),
            Path::new("/tmp/data/bash-completion/completions/codex-switch")
        );
        assert_eq!(
            completion_path(Some(OsStr::new("")), Some(OsStr::new("/tmp/home"))).unwrap(),
            expected
        );
        assert_eq!(
            completion_path(Some(OsStr::new("relative")), Some(OsStr::new("/tmp/home"))).unwrap(),
            expected
        );
        assert!(completion_path(Some(OsStr::new("relative")), None).is_err());
        assert!(completion_path(None, Some(OsStr::new("relative"))).is_err());
        assert!(completion_path(None, Some(OsStr::new(""))).is_err());
        assert!(completion_path(None, None).is_err());
    }

    #[test]
    fn dynamic_engine_preserves_import_filename_completion() {
        let (_ctx, base) = context("path-completion");
        std::fs::create_dir_all(&base).unwrap();
        std::fs::write(base.join("auth.json"), "{}").unwrap();
        let candidates = clap_complete::engine::complete(
            &mut crate::cli::Cli::command(),
            vec![
                "codex-switch".into(),
                "profile".into(),
                "import".into(),
                "codex".into(),
                "new".into(),
                base.join("au").into_os_string(),
            ],
            5,
            Some(&base),
        )
        .unwrap();
        assert!(candidates
            .iter()
            .any(|candidate| candidate.get_value() == base.join("auth.json").as_os_str()));
        std::fs::remove_dir_all(base).unwrap();
    }

    #[test]
    fn installer_is_idempotent_and_requires_force() {
        let (_ctx, base) = context("install");
        let path = base.join("nested/codex-switch");
        assert!(install_bash(&path, false).unwrap());
        assert_eq!(std::fs::read_to_string(&path).unwrap(), bash_script());
        assert!(!install_bash(&path, false).unwrap());
        std::fs::write(&path, "foreign\n").unwrap();
        assert!(install_bash(&path, false).is_err());
        assert_eq!(std::fs::read_to_string(&path).unwrap(), "foreign\n");
        assert!(install_bash(&path, true).unwrap());
        assert_eq!(std::fs::read_to_string(&path).unwrap(), bash_script());
        std::fs::remove_dir_all(base).unwrap();
    }

    #[test]
    fn installer_reports_invalid_paths_and_never_races_no_clobber() {
        let (_ctx, base) = context("errors");
        let blocker = base.join("blocker");
        std::fs::create_dir_all(&base).unwrap();
        std::fs::write(&blocker, "x").unwrap();
        assert!(install_bash(&blocker.join("codex-switch"), false).is_err());
        assert!(install_bash(Path::new(""), false).is_err());

        let raced = base.join("raced/codex-switch");
        let raced_for_hook = raced.clone();
        assert!(install_bash_with(&raced, false, || {
            std::fs::write(&raced_for_hook, "created concurrently\n").unwrap();
        })
        .is_err());
        assert_eq!(
            std::fs::read_to_string(&raced).unwrap(),
            "created concurrently\n"
        );
        assert!(bash_script().contains("CODEX_SWITCH_COMPLETE=bash codex-switch"));
        std::fs::remove_dir_all(base).unwrap();
    }

    #[cfg(unix)]
    #[test]
    fn installer_preserves_symlinks_without_force_and_replaces_with_force() {
        use std::os::unix::fs::symlink;

        let (_ctx, base) = context("symlink");
        std::fs::create_dir_all(&base).unwrap();
        let target = base.join("target");
        let path = base.join("codex-switch");
        std::fs::write(&target, "foreign\n").unwrap();
        symlink(&target, &path).unwrap();
        assert!(install_bash(&path, false).is_err());
        assert!(std::fs::symlink_metadata(&path)
            .unwrap()
            .file_type()
            .is_symlink());
        assert!(install_bash(&path, true).unwrap());
        assert!(!std::fs::symlink_metadata(&path)
            .unwrap()
            .file_type()
            .is_symlink());
        assert_eq!(std::fs::read_to_string(&path).unwrap(), bash_script());

        std::fs::remove_file(&path).unwrap();
        symlink(base.join("missing"), &path).unwrap();
        assert!(install_bash(&path, false).is_err());
        assert!(install_bash(&path, true).unwrap());
        std::fs::remove_dir_all(base).unwrap();
    }
}
